version: "1.0"
services:
  webapi:
    build:
      context: .
      dockerfile: CarsApi/Dockerfile
    ports:
      - "3030:3030"
  front:
    build:
      context: .
      dockerfile: TurboAz/Dockerfile
    ports:
      - "3000:3000"
